allowBuilds:
  core-js-pure: true
  esbuild: true
minimumReleaseAgeExclude:
  - pankosmia-rcl@0.7.1
  - pankosmia-juxta-muncher@0.2.10 || 0.2.11
  - pankosmia-translation_plan-muncher@0.2.5 || 0.2.6
  - pankosmia-bcv-muncher@0.2.1 || 0.2.2 || 0.2.3 || 0.2.4 || 0.2.5 || 0.2.6 || 0.2.7 || 0.2.8 || 0.2.9
  - pankosmia-obs-muncher@0.2.2 || 0.2.3 || 0.2.4 || 0.2.5 || 0.2.6

supportedArchitectures:
  os:
    - win32
    - linux
    - darwin
    - current
  cpu:
    - x64
    - arm64
